import type { Metadata } from "next";
import "@/app/globals.css";

import { Poppins as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import Wrapper from "@/components/wrapper";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import { ThemeProvider } from "@/components/themeProvider";

const fontSans = FontSans({
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	variable: "--font-sans",
	display: "swap",
	style: "normal",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={cn(
					"min-h-screen bg-background font-sans antialiased flex flex-col items-center",
					fontSans.variable,
					process.env.NODE_ENV === "development" && "debug-screens"
				)}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
				>
					<Wrapper>
						<Navbar />
						{children}
						<Footer />
					</Wrapper>
				</ThemeProvider>
			</body>
		</html>
	);
}
